# Generated by Django 4.2.7 on 2024-05-14 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cargo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('desc_cat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cli', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_cli', models.CharField(max_length=100)),
                ('email_cli', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut_emp', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_emp', models.CharField(max_length=100)),
                ('email_emp', models.EmailField(max_length=100)),
                ('telefono_emp', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(max_length=15)),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferreteria.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=10)),
                ('codigo_prod', models.CharField(max_length=10)),
                ('nombre_prod', models.CharField(max_length=100)),
                ('desc_prod', models.CharField(max_length=300)),
                ('precio_prod', models.IntegerField()),
                ('foto_prod', models.BinaryField(blank=True, null=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferreteria.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prov', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferreteria.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='tabla_test',
        ),
    ]
