# Generated by Django 4.2.2 on 2024-05-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0002_cargo_categoria_cliente_empleado_producto_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
