# Generated by Django 5.0.4 on 2024-05-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0005_remove_producto_categoria_alter_producto_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='foto_prod',
        ),
    ]
