# Generated by Django 5.0.4 on 2024-05-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0006_remove_producto_foto_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_prod',
            field=models.FloatField(),
        ),
    ]
